/**
 * Curated, deterministic word-pair collection for the secret-word mechanic.
 *
 * Each game picks ONE pair, then randomly decides which side is the MAIN word
 * (everyone but the imposter) and which is the ALTERNATE word (the imposter).
 *
 * Pairs are related enough that clues can naturally overlap, but different
 * enough that careful listening can expose the odd player. Obvious subtypes
 * and near-synonyms are avoided so a game is never trivial.
 */
export type WordPair = readonly [string, string];

export const WORD_PAIRS: readonly WordPair[] = [
  ["Pizza", "Burger"],
  ["Dog", "Wolf"],
  ["Beach", "Pool"],
  ["Coffee", "Tea"],
  ["Mountain", "Hill"],
  ["Laptop", "Tablet"],
  ["Football", "Basketball"],
  ["Movie", "TV Show"],
  ["Airport", "Train Station"],
  ["Doctor", "Nurse"],
  ["Rain", "Snow"],
  ["Ocean", "Lake"],
  ["Cake", "Ice Cream"],
  ["Car", "Motorcycle"],
  ["School", "College"],
  ["Cat", "Tiger"],
  ["Apple", "Orange"],
  ["Banana", "Mango"],
  ["Sun", "Moon"],
  ["Camera", "Phone"],
  ["Newspaper", "Magazine"],
  ["Train", "Bus"],
  ["Ship", "Boat"],
  ["Plane", "Helicopter"],
  ["Apartment", "House"],
  ["Hotel", "Motel"],
  ["Library", "Bookstore"],
  ["Hospital", "Clinic"],
  ["Restaurant", "Café"],
  ["Winter", "Summer"],
  ["Pancake", "Waffle"],
  ["Rabbit", "Hare"],
  ["Frog", "Toad"],
  ["Snake", "Lizard"],
  ["Alligator", "Crocodile"],
  ["Penguin", "Puffin"],
  ["Duck", "Goose"],
  ["Chicken", "Turkey"],
  ["Sheep", "Goat"],
  ["Rice", "Noodles"],
  ["Bread", "Croissant"],
  ["Vanilla", "Chocolate"],
  ["Strawberry", "Raspberry"],
  ["Lemon", "Lime"],
  ["Pineapple", "Coconut"],
  ["Boots", "Sneakers"],
  ["Jacket", "Sweater"],
  ["Gloves", "Mittens"],
  ["Bicycle", "Skateboard"],
  ["Subway", "Tram"],
  ["Cabin", "Tent"],
  ["Bridge", "Tunnel"],
  ["Park", "Playground"],
  ["Museum", "Gallery"],
  ["Mall", "Market"],
  ["Farm", "Garden"],
  ["Castle", "Palace"],
  ["Jungle", "Forest"],
  ["River", "Canal"],
  ["Snowboard", "Ski"],
  ["Chess", "Checkers"],
  ["Baseball", "Cricket"],
  ["Tennis", "Badminton"],
  ["Piano", "Organ"],
  ["Radio", "Stereo"],
  ["Map", "Compass"],
  ["Clock", "Watch"],
  ["Pen", "Pencil"],
  ["Spoon", "Chopsticks"],
  ["Cup", "Mug"],
  ["Stove", "Oven"],
  ["Microphone", "Megaphone"],
  ["Umbrella", "Raincoat"],
  ["Flashlight", "Lantern"],
  ["Shampoo", "Conditioner"],
  ["Backpack", "Suitcase"],
  ["Sofa", "Armchair"],
  ["Lamp", "Candle"],
  ["Sunscreen", "Sunglasses"],
] as const;